// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.DAL;

public partial class Logistic
{
    [Key]
    public int LogisticsId { get; set; }

    [Required]
    [StringLength(300)]
    public string VehicleDescription { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string VehicleNumberPlate { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string FromString { get; set; }

    public int? WarehouseFromId { get; set; }

    public int? SupplierFromId { get; set; }

    [Column(TypeName = "decimal(10, 3)")]
    public decimal? SupplierCost { get; set; }

    public int WarehouseDeliveryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? WarehouseDispatchDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDelivered { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DueDate { get; set; }

    [ForeignKey("SupplierFromId")]
    [InverseProperty("Logistics")]
    public virtual Supplier SupplierFrom { get; set; }

    [ForeignKey("WarehouseDeliveryId")]
    [InverseProperty("LogisticWarehouseDeliveries")]
    public virtual Warehouse WarehouseDelivery { get; set; }

    [ForeignKey("WarehouseFromId")]
    [InverseProperty("LogisticWarehouseFroms")]
    public virtual Warehouse WarehouseFrom { get; set; }
}