// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.DAL;

[Keyless]
[Table("StockItem")]
public partial class StockItem
{
    public int StockItemId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string StockItemType { get; set; }

    public int? WarehouseId { get; set; }

    public int? SupplierId { get; set; }

    public int? LogisticsId { get; set; }

    public int ItemId { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("ItemId")]
    public virtual Item Item { get; set; }

    [ForeignKey("LogisticsId")]
    public virtual Logistic Logistics { get; set; }

    [ForeignKey("SupplierId")]
    public virtual Supplier Supplier { get; set; }

    [ForeignKey("WarehouseId")]
    public virtual Warehouse Warehouse { get; set; }
}