// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.DAL;

[Table("Supplier")]
public partial class Supplier
{
    [Key]
    public int SupplierId { get; set; }

    public int Code { get; set; }

    [Required]
    [StringLength(400)]
    public string Name { get; set; }

    [Required]
    [StringLength(12)]
    [Unicode(false)]
    public string Telephone { get; set; }

    [InverseProperty("SupplierFrom")]
    public virtual ICollection<Logistic> Logistics { get; set; } = new List<Logistic>();

    [InverseProperty("Supplier")]
    public virtual ICollection<SupplierLocation> SupplierLocations { get; set; } = new List<SupplierLocation>();
}