// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.Shared.Entities
{
    public partial class Employee
    {
        public Employee()
        {
            Order = new HashSet<Order>();
        }

        [Key]
        public int EmployeeId { get; set; }
        [StringLength(40)]
        public string Name { get; set; }
        [StringLength(40)]
        public string Surname { get; set; }
        public bool IsDeleted { get; set; }

        [InverseProperty("Employee")]
        public virtual ICollection<Order> Order { get; set; }
    }
}