// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.Shared.Entities
{
    [Index("ItemId", Name = "IX_OrderItems_ItemId")]
    [Index("OrderId", Name = "IX_OrderItems_OrderId")]
    public partial class OrderItem
    {
        [Key]
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("OrderItem")]
        public virtual Item Item { get; set; }
        [ForeignKey("OrderId")]
        [InverseProperty("OrderItem")]
        public virtual Order Order { get; set; }
    }
}