// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopWorld.Shared.Entities
{
    [Index("CustomerId", Name = "IX_Orders_CustomerId")]
    [Index("EmployeeId", Name = "IX_Orders_EmployeeId")]
    public partial class Order
    {
        public Order()
        {
            OrderItem = new HashSet<OrderItem>();
        }

        [Key]
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? DateFulfilled { get; set; }
        public DateTime DateCreated { get; set; }
        public Guid OrderReference { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal VAT { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Subtotal { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal GrandTotal { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("Order")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("EmployeeId")]
        [InverseProperty("Order")]
        public virtual Employee Employee { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}